FROM nginx 
label email=ashutoshh@linux.com 
COPY project-website-template /usr/share/nginx/html/
# copy can add file or folder to docker image 
# if we are not using CMD so base image cmd will be inherited 
