version: '3.8'
volumes: # creating volume 
  ashu-vol-db: # name of volume 
  ashu-gen-data:
services:
  ashu-ui-app:
    image: adminer # open source sample UI image 
    volumes: # for mounting 
    - ashu-gen-data:/mnt/ok
    container_name: ashu-ui-c1
    ports:
    - 1234:8080 
    depends_on:
    - ashu-db-app
  ashu-db-app:
    image: mysql
    container_name: ashu-db-c1
    environment: # create / update ENV variable in container 
      MYSQL_ROOT_PASSWORD: "MobiDb@098"
    env_file: 
    - .cred.env 
    volumes: # mounting volume
    - ashu-vol-db:/var/lib/mysql/ # default mysql data location 
    - ashu-gen-data:/var/log/mysql
      
    